# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: C'est la vie.
email: linamy85@gmail.com
description: > # document head meta: for search result
  Life recording & study sharing of Yu-Hsuan Lin,
  who is a tech girl of curiosity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username: linamy85 

# Build settings
#markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,md"
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  sass_dir: assets/_sass


images: '/assets/images'
